name: Kits
version: ${project.version}
main: br.ynicollas.kits.KitsPlugin
author: yNicollas
website: https://github.com/nicollasgtb
api-version: '1.13'
load: STARTUP
commands:
  createkit:
    aliases: [criarkit]
  deletekit:
    aliases: [delkit]
  editkit:
    aliases: [editarkit]
  givekit:
    aliases: [darkit]
  kit:
    aliases: []
  viewkit:
    aliases: [verkit]