name: Kits
version: ${version}
main: com.codenicollas.kits.KitsPlugin
author: codenicollas
website: https://github.com/codenicollas
api-version: '1.13'
load: POSTWORLD
commands:
  createkit:
    aliases: [criarkit]
  deletekit:
    aliases: [delkit]
  editkit:
    aliases: [editarkit]
  givekit:
    aliases: [darkit]
  kit:
    aliases: []
  viewkit:
    aliases: [verkit]